### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by ddiaz2380** [imMaturana/nixos-config#1]
error: access to absolute path '/nix/store/xbxrckxsjhq60bx19vbr7hnbiasxdjcl-vscode-extensions/share/vscode/extensions' is forbidden in pure eval mode (use '--impure' to override)
(use '--show-trace' to show detailed location information)

Tried several times and always gives the same error.
I wanted to try your dotfiles since I love gruvbox and minimalist.
Thanks!

**Comment by imMaturana** [comment]
Hm, I've never had an issue like this, I'll investigate.
For now, you can try commenting the VSCode import in `users/maturana/configs/default.nix` file.

I need to update the README, I will do that asap.

**Comment by imMaturana** [comment]
Also, I highly recommend that instead of copying all this configuration, just copy snippets, maybe that avoid some errors.

**Comment by ddiaz2380** [comment]
I'll try it, thanks for answering!
